### PR TITLE
Transcribe Appendices to Markdown, add individual forms 1-20

### PR DESCRIPTION
**Pull request by LoneRifle**
TODO: Rework Appendix A into individual sample/form downloads

### CODE REVIEW

**Comment by pregnantboy** [comment]
Also, propose to remove Appendix B, C ,D pdf files

**Comment by pregnantboy** [comment]
@lisatjide plz review

**Comment by LoneRifle** [comment]
Er not sure what's going on right now, but GitHub is complaining of merge conflicts. @pregnantboy can you address please?

**Comment by lisatjide** [comment]
> Er not sure what's going on right now, but GitHub is complaining of merge conflicts. @pregnantboy can you address please?

Whops, just saw this one. I think it's because I removed the appendices?

**Pull request merged**
